version: '3.8'

services:
  # Development service
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: serve
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    environment:
      - NODE_ENV=development
    command: npm run dev

  # Production service
  app-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production

  # Testing service
  app-test:
    build:
      context: .
      dockerfile: Dockerfile
      target: serve
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=test
    command: npm run preview

  # Nginx reverse proxy (optional)
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx_logs:/var/log/nginx
    depends_on:
      - app-prod
    profiles:
      - production 